apiVersion: v1
kind: Service
metadata:
  name: cpx-service
  annotations:
    status.service.com/endpoint-type: hostname
    status.service.com/endpoint: "cpx.status-update.com"
  labels:
    app: cpx-service
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - port: 80
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  selector:
    app: cpx-ingress
