kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: status-updater
rules:
  - apiGroups: [""]
    resources: ["services/status"]
    verbs: ["update", "patch"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch", "patch"]
---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: status-updater
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: status-updater
subjects:
- kind: ServiceAccount
  name: status-updater
  namespace: default
apiVersion: rbac.authorization.k8s.io/v1

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: status-updater
  namespace: default

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: status-updater
spec:
  selector:
    matchLabels:
      app: status-updater
  replicas: 1
  template:
    metadata:
      name: status-updater
      labels:
        app: status-updater
      annotations:
    spec:
      serviceAccountName: status-updater
      containers:
        - name: status-updater
          image: "raghulc/status-patcher:v2.0"
          env:
          # These ENV vars are optional
          - name: "LOADBALANCER_HOSTNAME_ANNOTATION"
            value: "status.service.com/loadbalancer-hostname"
          - name: "LOADBALANCER_IP_ANNOTATION"
            value: "status.service.com/loadbalancer-ip"
          imagePullPolicy: Always
